[tool.poetry]
name = "progress"
version = "0.1.0"
description = ""
authors = ["SagidullinEmil <se12373@auca.kg>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.2"
pillow = "^10.2.0"
django-jet-reboot = "^1.3.7"
google-api-python-client = "1.4.1"
django-ckeditor-5 = "^0.2.11"
<<<<<<< HEAD
djangorestframework = "^3.14.0"
<<<<<<< HEAD
=======
django-filter = "^23.5"
>>>>>>> 481b372 ( On branch page_editor)
=======
django-environ = "^0.11.2"
>>>>>>> 975b037 ( #6 Добавлен .env; Изменены choice классы)


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
